const names={garage:'CarFront',dashboard:'LayoutDashboard',wallet:'Wallet',calendar:'CalendarDays',settings:'Settings',plus:'Plus',fuel:'Fuel',trend:'TrendingUp',road:'Gauge',close:'X',tools:'Wrench',edit:'Pencil',trash:'Trash2',check:'Check'};
const icon=n=>lucide.createElement(lucide.icons[names[n]||'Wallet'],{'aria-hidden':'true'}).outerHTML;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>(Number(v||0)/100).toLocaleString('it-IT',{style:'currency',currency:'EUR'});
const decimal=(v,d=1)=>Number(v).toLocaleString('it-IT',{minimumFractionDigits:d,maximumFractionDigits:d});
const today=()=>new Date().toLocaleDateString('en-CA');
const pages=[['Panoramica','dashboard'],['Movimenti','wallet'],['Scadenze','calendar'],['Garage','garage'],['Impostazioni','settings']];
const kinds={refuels:'Rifornimento',expenses:'Spesa',maintenances:'Manutenzione',reminders:'Scadenza'};
let data=null,current='Panoramica',period='month',typeFilter='',paymentFilter='',editing=null,saving=false;
const modal=document.querySelector('dialog');
const css=document.createElement('style');css.textContent=`.record-list{border-top:1px solid var(--line)}.record{display:grid;grid-template-columns:1fr auto auto;gap:16px;align-items:center;padding:18px 0;border-bottom:1px solid var(--line)}.record-title{font-size:15px;font-weight:600;overflow-wrap:anywhere}.record-meta{font-size:13px;color:var(--muted);margin-top:6px;line-height:1.6}.record-actions{display:flex;gap:4px}.icon-button{padding:9px;background:white;border:1px solid var(--line);border-radius:5px;display:inline-flex;color:#536075}.danger{color:#b32635}.amount{font-weight:650;white-space:nowrap}.error-box{padding:20px;background:#fff0f1;color:#982636;border:1px solid #f0ccd0;border-radius:6px}.fields label.check{display:flex;align-items:center;gap:10px}.check input{width:18px;height:18px}.fields textarea{padding:11px;border:1px solid #cfd5de;border-radius:5px;width:100%;min-height:70px;font:inherit}.bars{height:220px;display:flex;gap:14px;align-items:end;padding:12px 0 32px;margin-bottom:35px;border-bottom:1px solid var(--line)}.bar-wrap{height:100%;flex:1;display:flex;flex-direction:column;justify-content:end;align-items:center;gap:8px;min-width:0}.bar{width:65%;background:var(--blue);min-height:2px;border-radius:3px 3px 0 0}.bar-wrap small{font-size:12px;color:var(--muted)}.bar-value{font-size:12px}.badge{font-size:12px;color:#9c3434;background:#fff0f1;padding:3px 6px;border-radius:3px}.badge.done{color:#246147;background:#e9f6ed}#form-error{color:#a22f39}.settings-form{max-width:650px}select{max-width:100%}button:disabled{opacity:.5;cursor:wait}.fields .primary{min-height:44px}.category-row{display:flex;justify-content:space-between;padding:10px 0;font-size:14px;border-bottom:1px solid var(--line)}@media(max-width:720px){.record{grid-template-columns:1fr auto;gap:10px}.record-actions{grid-column:1/-1;justify-content:flex-end}.bar-value{font-size:10px}.bars{gap:7px}.fields{grid-template-columns:1fr}.fields .wide{grid-column:auto}}`;
document.head.append(css);
function icons(){document.querySelectorAll('[data-icon]').forEach(el=>el.innerHTML=icon(el.dataset.icon))}
function notify(message){const el=document.querySelector('.toast');el.textContent=message;el.hidden=false;setTimeout(()=>el.hidden=true,5000)}
async function api(path,method='GET',body){const response=await fetch('/api/'+path,{method,headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});let result;try{result=await response.json()}catch{throw new Error('Connessione interrotta. Ricarica la pagina.')}if(!response.ok)throw new Error(result.error||'Operazione non riuscita');return result}
async function load(){data=await api('data');render(current)}
function vehicle(){return data.vehicles.find(v=>v.is_active)||data.vehicles[0]}
function records(table){return data[table].filter(r=>r.vehicle_id===vehicle()?.id)}
function mileage(){return Math.max(vehicle()?.initial_mileage_km||0,...['refuels','expenses','maintenances'].flatMap(t=>records(t).map(r=>r.odometer_km||0)))}
function movements(){return ['refuels','expenses','maintenances'].flatMap(table=>records(table).map(r=>({...r,table,cents:r.total_cents??r.amount_cents??r.cost_cents,label:table==='refuels'?'Rifornimento':r.description}))).sort((a,b)=>b.date.localeCompare(a.date)||b.id.localeCompare(a.id))}
function inPeriod(row){const d=new Date(row.date),now=new Date();return period==='all'||d.getFullYear()===now.getFullYear()&&(period==='year'||d.getMonth()===now.getMonth())}
function consumption(){const rows=records('refuels').slice().sort((a,b)=>a.odometer_km-b.odometer_km);let previous=null,liters=0,totalLiters=0,km=0;for(const r of rows){if(!previous){if(r.full_tank)previous=r;continue}liters+=r.liters_ml/1000;if(r.full_tank){const distance=r.odometer_km-previous.odometer_km;if(distance>0&&liters>0){km+=distance;totalLiters+=liters}previous=r;liters=0}}return totalLiters?km/totalLiters:null}
function empty(title,text,action=''){return `<div class="empty"><div class="empty-icon">${icon('wallet')}</div><h3>${esc(title)}</h3><p>${esc(text)}</p>${action}</div>`}
function addButton(table='refuels'){return `<button class="primary" onclick="openEntry('${table}')">${icon('plus')} Aggiungi</button>`}
function pageHeading(title,sub,action=addButton()){return `<div class="page-top"><div><h1>${esc(title)}</h1><p class="sub muted">${esc(sub)}</p></div>${action}</div>`}
function periodButtons(){return `<div class="period">${[['month','Questo mese'],['year',"Quest'anno"],['all','Tutto il periodo']].map(([key,label])=>`<button class="${period===key?'selected':''}" onclick="period='${key}';render(current)">${label}</button>`).join('')}</div>`}
function recordRows(rows){if(!rows.length)return empty('Nessun movimento','Aggiungi il primo rifornimento, una spesa o una manutenzione.');return `<div class="record-list">${rows.map(r=>`<article class="record"><div><div class="record-title">${esc(r.label)}</div><div class="record-meta">${new Date(r.date).toLocaleDateString('it-IT')} · ${kinds[r.table]} · ${esc(r.payment_method||'—')}${r.table==='refuels'?`<br>${decimal(r.liters_ml/1000,3)} L · ${decimal(r.total_cents*10/r.liters_ml,3)} €/l · ${r.odometer_km.toLocaleString('it-IT')} km`:''}</div></div><span class="amount">${money(r.cents)}</span><div class="record-actions"><button class="icon-button" aria-label="Modifica ${esc(r.label)}" title="Modifica" onclick="openEntry('${r.table}','${r.id}')">${icon('edit')}</button><button class="icon-button danger" title="Elimina" aria-label="Elimina ${esc(r.label)}" onclick="removeEntry('${r.table}','${r.id}')">${icon('trash')}</button></div></article>`).join('')}</div>`}
function remindersList(limit){const rows=records('reminders').slice().sort((a,b)=>(a.status==='COMPLETATA')-(b.status==='COMPLETATA')||a.due_date.localeCompare(b.due_date));const list=limit?rows.filter(r=>r.status!=='COMPLETATA').slice(0,limit):rows;if(!list.length)return empty('Nessuna scadenza','Bollo, assicurazione, revisione e tagliandi.');return list.map(r=>{const done=r.status==='COMPLETATA',overdue=r.due_date<today()||r.due_mileage_km!=null&&r.due_mileage_km<=mileage();return `<article class="record"><div><div class="record-title">${esc(r.title)}</div><div class="record-meta">${new Date(r.due_date+'T12:00:00').toLocaleDateString('it-IT')}${r.due_mileage_km?' · '+r.due_mileage_km+' km':''}</div></div><span class="badge ${done?'done':''}">${done?'Completata':overdue?'Scaduta':'In programma'}</span><div class="record-actions">${!done?`<button class="icon-button" title="Segna completata" aria-label="Completa ${esc(r.title)}" onclick="completeReminder('${r.id}',this)">${icon('check')}</button>`:''}<button class="icon-button" title="Modifica" aria-label="Modifica ${esc(r.title)}" onclick="openEntry('reminders','${r.id}')">${icon('edit')}</button><button class="icon-button danger" title="Elimina" aria-label="Elimina ${esc(r.title)}" onclick="removeEntry('reminders','${r.id}')">${icon('trash')}</button></div></article>`}).join('')}
function chart(rows){if(!rows.length)return empty('Ancora nessuna spesa','L’andamento apparirà dopo la prima registrazione.');const now=new Date();const months=Array.from({length:6},(_,i)=>new Date(now.getFullYear(),now.getMonth()-5+i,1));const totals=months.map(d=>rows.filter(r=>new Date(r.date).getFullYear()===d.getFullYear()&&new Date(r.date).getMonth()===d.getMonth()).reduce((s,r)=>s+r.cents,0));const max=Math.max(...totals,1);return `<div class="bars" aria-label="Spese degli ultimi sei mesi">${months.map((d,i)=>`<div class="bar-wrap"><span class="bar-value">${money(totals[i])}</span><div class="bar" style="height:${totals[i]/max*140}px"></div><small>${d.toLocaleDateString('it-IT',{month:'short'})}</small></div>`).join('')}</div>`}
function render(page){current=page;document.querySelector('nav').innerHTML=pages.map(([p,i])=>`<button class="${p===page?'active':''}" ${p===page?'aria-current="page"':''} onclick="render('${p}')">${icon(i)}<span>${p}</span></button>`).join('');document.querySelector('#breadcrumb').textContent=page;if(!data)return;const v=vehicle();if(!v){document.querySelector('#content').innerHTML=empty('Auto non disponibile','Controlla la configurazione del garage.');return}document.querySelector('.vehicle-mini').innerHTML=`<strong>${esc(v.make+' '+v.model)}</strong><span>${esc(v.year)} · ${esc(v.fuel_type)}</span>`;const all=movements(),filtered=all.filter(inPeriod);let body='';
  if(page==='Panoramica'){const fuel=filtered.filter(r=>r.table==='refuels'),avg=consumption();body=pageHeading('La tua auto, a colpo d’occhio',v.make+' '+v.model+' · '+v.year+' · '+v.fuel_type)+periodButtons()+`<div class="stats">${[['wallet','Spese totali',money(filtered.reduce((s,r)=>s+r.cents,0)),filtered.length+' movimenti'],['fuel','Carburante',money(fuel.reduce((s,r)=>s+r.cents,0)),decimal(fuel.reduce((s,r)=>s+r.liters_ml/1000,0))+' litri'],['trend','Consumo medio',avg?decimal(avg)+' km/l':'—','Tra pieni completi · storico'],['road','Chilometri',mileage().toLocaleString('it-IT')+' km','Ultima lettura registrata']].map(([i,l,val,s])=>`<div class="stat"><div class="stat-label">${icon(i)}${l}</div><strong>${val}</strong><small>${s}</small></div>`).join('')}</div><div class="grid"><section><div class="section-title"><h2>Spese degli ultimi sei mesi</h2></div>${chart(all)}<div class="section-title divider"><h2>Ultimi movimenti</h2><button class="text-button" onclick="render('Movimenti')">Vedi tutti</button></div>${recordRows(all.slice(0,5))}</section><section><div class="section-title"><h2>Prossime scadenze</h2><button class="text-button" onclick="render('Scadenze')">Vedi tutte</button></div>${remindersList(3)}<div class="section-title divider"><h2>Registra un movimento</h2></div><div class="mini-actions">${[['refuels','fuel'],['expenses','wallet'],['maintenances','tools']].map(([t,i])=>`<button onclick="openEntry('${t}')">${icon(i)}<span>${kinds[t]}</span><span>+</span></button>`).join('')}</div></section></div>`}
  if(page==='Movimenti'){const payments=[...new Set(all.map(r=>r.payment_method).filter(Boolean))];body=pageHeading('Movimenti','Tutte le spese della tua auto, in un unico registro.')+periodButtons()+`<div class="toolbar"><select aria-label="Tipo movimento" onchange="typeFilter=this.value;render(current)"><option value="">Tutti i movimenti</option>${Object.entries(kinds).filter(([k])=>k!=='reminders').map(([k,l])=>`<option value="${k}" ${typeFilter===k?'selected':''}>${l}</option>`).join('')}</select><select aria-label="Pagamento" onchange="paymentFilter=this.value;render(current)"><option value="">Tutti i pagamenti</option>${payments.map(p=>`<option ${p===paymentFilter?'selected':''}>${esc(p)}</option>`).join('')}</select></div>`+recordRows(filtered.filter(r=>(!typeFilter||r.table===typeFilter)&&(!paymentFilter||r.payment_method===paymentFilter)))}
  if(page==='Scadenze')body=pageHeading('Scadenze','Gli appuntamenti della tua auto, in ordine di urgenza.',addButton('reminders'))+remindersList();
  if(page==='Garage')body=pageHeading(v.make+' '+v.model,'Il profilo della tua auto.',`<button class="primary" onclick="openEntry('vehicles','${v.id}')">${icon('edit')} Modifica auto</button>`)+`<dl class="details">${[['Marca',v.make],['Modello',v.model],['Anno',v.year],['Alimentazione',v.fuel_type],['Targa',v.plate||'Da inserire'],['Chilometri iniziali',v.initial_mileage_km.toLocaleString('it-IT')],['Chilometri attuali',mileage().toLocaleString('it-IT')]].map(([a,b])=>`<div><dt>${a}</dt><dd>${esc(b)}</dd></div>`).join('')}</dl>`;
  if(page==='Impostazioni')body=pageHeading('Impostazioni','Le tue carte e i metodi di pagamento.',addButton('payment_methods'))+(data.payment_methods.length?data.payment_methods.map(r=>`<article class="record"><strong>${esc(r.name)}</strong><div></div><div class="record-actions"><button class="icon-button" aria-label="Modifica carta ${esc(r.name)}" title="Modifica" onclick="openEntry('payment_methods','${r.id}')">${icon('edit')}</button><button class="icon-button danger" aria-label="Elimina carta ${esc(r.name)}" title="Elimina" onclick="removeEntry('payment_methods','${r.id}')">${icon('trash')}</button></div></article>`).join(''):empty('Nessuna carta salvata','Aggiungi il nome con cui riconosci la carta.'))+`<dl class="details"><div><dt>Valuta</dt><dd>Euro (€)</dd></div><div><dt>Consumo medio</dt><dd>km/l</dd></div><div><dt>Accesso</dt><dd>Privato</dd></div></dl>`;
  document.querySelector('#content').innerHTML=body;icons();
}
function field(name,label,value='',type='text',extra=''){return `<label>${label}<input name="${name}" type="${type}" value="${esc(value)}" ${extra}></label>`}
function select(name,label,options,value){return `<label>${label}<select name="${name}">${options.map(([v,l])=>`<option value="${esc(v)}" ${v===value?'selected':''}>${esc(l)}</option>`).join('')}</select></label>`}
function openEntry(table,id=null){if(saving)return;const r=id?data[table].find(x=>x.id===id):{};if(!r)return;editing={table,id};document.querySelector('#modal-title').textContent=(id?'Modifica ':'Aggiungi ')+(kinds[table]||({vehicles:'auto',payment_methods:'carta'})[table]);let fields='';
  if(table==='payment_methods')fields=field('name','Nome carta / metodo',r.name||'','text','required maxlength="80" placeholder="Es. Revolut"');
  else if(table==='vehicles')fields=field('make','Marca',r.make,'text','required')+field('model','Modello',r.model,'text','required')+field('year','Anno',r.year,'number','required min="1900" max="2100"')+field('plate','Targa',r.plate)+select('fuel_type','Alimentazione',['BENZINA','DIESEL','IBRIDA','ELETTRICA','GPL','METANO'].map(x=>[x,x]),r.fuel_type)+field('initial_mileage_km','Chilometri iniziali',r.initial_mileage_km,'number','required min="0" step="1"');
  else if(table==='reminders')fields=field('title','Titolo',r.title,'text','required')+field('due_date','Scadenza',r.due_date||today(),'date','required')+field('due_mileage_km','Scadenza km (facoltativa)',r.due_mileage_km??'','number','min="0" step="1"')+select('periodicity','Periodicità',['NESSUNA','MENSILE','ANNUALE','BIENNALE'].map(x=>[x,x]),r.periodicity||'NESSUNA')+select('status','Stato',[['FUTURA','Da completare'],['COMPLETATA','Completata']],r.status==='COMPLETATA'?'COMPLETATA':'FUTURA');
  else{fields=(!id?select('entry_type','Tipo',Object.entries(kinds).filter(([k])=>k!=='reminders'),table):'')+field('date','Data',r.date?.slice(0,10)||today(),'date','required')+field('odometer_km','Chilometri',r.odometer_km??'','number','required min="0" step="1"');if(table==='refuels')fields+=field('liters','Litri',r.liters_ml?r.liters_ml/1000:'','number','required min="0.001" step="0.001" inputmode="decimal"');fields+=field('amount','Importo (€)',id?(r.total_cents??r.amount_cents??r.cost_cents)/100:'','number',`required min="${table==='maintenances'?'0':'0.01'}" step="0.01" inputmode="decimal"`)+field('payment_method','Carta / metodo di pagamento',r.payment_method||'','text','required list="payments"')+`<datalist id="payments"><option value="Contanti">${data.payment_methods.map(p=>`<option value="${esc(p.name)}">`).join('')}</datalist>`;if(table==='refuels')fields+=field('station','Distributore',r.station)+field('location','Località',r.location)+`<label class="check wide"><input type="checkbox" name="full_tank" ${r.full_tank?'checked':''}>Pieno completo</label>`;else{fields+=field('description','Descrizione',r.description,'text','required');if(table==='expenses')fields+=select('category_id','Categoria',data.expense_categories.filter(c=>!c.is_fuel).map(c=>[c.id,c.name]),r.category_id);else fields+=field('type','Tipo manutenzione',r.type,'text','required')+field('workshop','Officina',r.workshop)}}
  if(table!=='payment_methods')fields+=`<label class="wide">Note<textarea name="notes">${esc(r.notes)}</textarea></label>`;
  document.querySelector('#fields').innerHTML=fields;document.querySelector('#fields select[name="entry_type"]')?.addEventListener('change',e=>openEntry(e.target.value));document.querySelector('#fuel-result').hidden=table!=='refuels';document.querySelector('#form-error').textContent='';document.querySelector('#entry-form').oninput=calc;calc();icons();if(!modal.open)modal.showModal();
}
function calc(){const form=document.querySelector('#entry-form'),liters=Number(form.elements.liters?.value),amount=Number(form.elements.amount?.value);const p=document.querySelector('#price');p.setAttribute('aria-live','polite');p.textContent=Number.isFinite(liters)&&liters>0&&Number.isFinite(amount)&&amount>0?decimal(amount/liters,3)+' €/l':'—'}
document.querySelector('#entry-form').addEventListener('submit',async event=>{event.preventDefault();if(saving||!editing)return;const form=event.target,body=Object.fromEntries(new FormData(form)),{table,id}=editing;delete body.entry_type;body.vehicle_id=vehicle().id;if(table==='refuels'){body.liters_ml=Math.round(Number(body.liters)*1000);body.total_cents=Math.round(Number(body.amount)*100);body.full_tank=form.elements.full_tank.checked}else if(table==='expenses')body.amount_cents=Math.round(Number(body.amount)*100);else if(table==='maintenances')body.cost_cents=Math.round(Number(body.amount)*100);saving=true;const btn=form.querySelector('button[type="submit"]');btn.disabled=true;btn.textContent='Salvataggio…';try{await api(table+(id?'/'+id:''),id?'PATCH':'POST',body);modal.close();notify('Salvato');try{await load()}catch{notify('Salvato. Ricarica la pagina per aggiornare l’elenco.')}}catch(e){document.querySelector('#form-error').textContent=e.message}finally{saving=false;btn.disabled=false;btn.textContent='Salva'}});
async function removeEntry(table,id){if(saving)return;const row=data[table].find(r=>r.id===id);if(!row)return;const confirmDialog=document.createElement('dialog');confirmDialog.innerHTML=`<h2>Eliminare questa voce?</h2><p>${esc(row.title||row.description||row.name||kinds[table])}</p><p class="muted">L’eliminazione è definitiva. Le altre registrazioni rimarranno invariate.</p><div style="display:flex;gap:12px;justify-content:flex-end"><button class="secondary" data-cancel>Annulla</button><button class="primary" data-confirm>Elimina</button></div><p role="alert"></p>`;document.body.append(confirmDialog);confirmDialog.onclose=()=>confirmDialog.remove();confirmDialog.querySelector('[data-cancel]').onclick=()=>confirmDialog.close();confirmDialog.querySelector('[data-confirm]').onclick=async e=>{e.target.disabled=true;saving=true;try{await api(table+'/'+id,'DELETE');confirmDialog.close();notify('Voce eliminata');await load()}catch(err){confirmDialog.querySelector('[role="alert"]').textContent=err.message;e.target.disabled=false}finally{saving=false}};confirmDialog.showModal()}
async function completeReminder(id,button){button.disabled=true;try{const row=records('reminders').find(r=>r.id===id);await api('reminders/'+id,'PATCH',{...row,status:'COMPLETATA'});await load();notify('Scadenza completata')}catch(e){notify(e.message);button.disabled=false}}
render(current);document.querySelector('#content').innerHTML='<p role="status">Caricamento del garage…</p>';load().catch(e=>{document.querySelector('#content').innerHTML=`<div class="error-box" role="alert">${esc(e.message)} <button class="secondary" onclick="location.reload()">Riprova</button></div>`});
if(document.modelContext?.registerTool){for(const tool of [{name:'read_garage_summary',description:'Read current vehicle and movement totals without changing data.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:async()=>{await load();return{vehicle:vehicle()?.model,movements:movements().length,total_cents:movements().reduce((s,r)=>s+r.cents,0)}}},{name:'open_garage_section',description:'Navigate to a garage section without saving any data.',inputSchema:{type:'object',properties:{section:{type:'string',enum:pages.map(([p])=>p)}},required:['section'],additionalProperties:false},annotations:{readOnlyHint:true},execute:async input=>{if(!pages.some(([p])=>p===input.section))throw new Error('Sezione non valida');render(input.section);return{section:current}}}]){try{Promise.resolve(document.modelContext.registerTool(tool)).catch(()=>{})}catch{}}}
